-- MySQL Script generated by MySQL Workbench
-- Thu Apr  4 18:51:04 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tt
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tt` ;
USE `tt` ;

-- -----------------------------------------------------
-- Table `tt`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tt`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` CHAR(50) COLLATE 'utf8mb3_spanish_ci' NOT NULL,
  `usuario` CHAR(20) COLLATE 'utf8mb3_spanish_ci' NOT NULL,
  `correo` CHAR(50) COLLATE 'utf8mb3_spanish_ci' NOT NULL,
  `contraseña` CHAR(80) COLLATE 'utf8mb3_spanish_ci' NOT NULL,
  `codigoVerificacion` CHAR(10) COLLATE 'utf8mb3_spanish_ci' NOT NULL,
  `verificado` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 3;


-- -----------------------------------------------------
-- Table `tt`.`articulonoticia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tt`.`articulonoticia` (
  `idArticulo` INT NOT NULL AUTO_INCREMENT,
  `titulo` CHAR(200) COLLATE 'utf8mb3_spanish_ci' NOT NULL,
  `contenido` TEXT COLLATE 'utf8mb3_spanish_ci' NOT NULL,
  `fecha` TEXT COLLATE 'utf8mb3_spanish_ci' NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idArticulo`),
  INDEX `fk_usuario_articulo` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_articulo`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `tt`.`usuario` (`idUsuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 6;


-- -----------------------------------------------------
-- Table `tt`.`calificacionnoticia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tt`.`calificacionnoticia` (
  `idCalificacion` INT NOT NULL,
  `puntuacion` INT NULL DEFAULT NULL,
  `idUsuario` INT NOT NULL,
  `idArticulo` INT NOT NULL,
  PRIMARY KEY (`idCalificacion`),
  INDEX `idUsuario` (`idUsuario` ASC) VISIBLE,
  INDEX `calificacionnoticia_ibfk_2` (`idArticulo` ASC) VISIBLE,
  CONSTRAINT `calificacionnoticia_ibfk_1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `tt`.`usuario` (`idUsuario`),
  CONSTRAINT `calificacionnoticia_ibfk_2`
    FOREIGN KEY (`idArticulo`)
    REFERENCES `tt`.`articulonoticia` (`idArticulo`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
